social:

- {icon: 'telegram', link: 'https://t.me/layercv', class: fab}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/wildchlamydia/', class: fab}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/%D0%B8%D1%80%D0%B8%D0%BD%D0%B0-%D1%82%D0%BE%D0%BB%D1%81%D1%82%D1%8B%D1%85-2a76111a2/', class: fab}
- {icon: 'facebook', link: 'https://www.facebook.com/WildChlamydia', class: fab}
- {icon: 'telegram', link: 'https://t.me/wild_chlamydia_work', class: fab}
- {icon: 'telegram', link: 'https://t.me/IrinaKrasnova', class: fab}
- {icon: 'envelope', link: 'mailto:mvkuprashevich@gmail.com', class: fa}
- {icon: 'envelope', link: 'mailto:irinakr4snova@gmail.com', class: fa}
